# Generated by Django 3.2.8 on 2022-11-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_zohoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='redirecturi',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
