# Generated by Django 4.1.3 on 2022-11-22 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='item_waight',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ordersdelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.FloatField(default=0)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('collectedAmount', models.FloatField(default=0)),
                ('orderValue', models.CharField(blank=True, max_length=50, null=True)),
                ('invoiceNo', models.CharField(blank=True, max_length=50, null=True)),
                ('invoiceID', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=30, null=True)),
                ('upi', models.FloatField(default=0)),
                ('cash', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.orderinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicleinfo')),
            ],
        ),
    ]
