# Generated by Django 4.1.3 on 2022-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_iteminfo_item_waight_ordersdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdelivery',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
    ]
