# Generated by Django 4.1.3 on 2022-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ordersdelivery_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdelivery',
            old_name='invoiceID',
            new_name='invoice_balance',
        ),
        migrations.RenameField(
            model_name='ordersdelivery',
            old_name='invoiceNo',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='ordersdelivery',
            old_name='location',
            new_name='invoice_number',
        ),
        migrations.RenameField(
            model_name='ordersdelivery',
            old_name='orderValue',
            new_name='invoice_total',
        ),
        migrations.RemoveField(
            model_name='ordersdelivery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ordersdelivery',
            name='longitude',
        ),
        migrations.AddField(
            model_name='ordersdelivery',
            name='location_coordinates',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ordersdelivery',
            name='location_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersdelivery',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
