# Generated by Django 4.1.3 on 2022-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_orderinfo_location_url_alter_zohoaccount_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdelivery',
            name='serialno',
            field=models.IntegerField(default=0),
        ),
    ]
